// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 922 07/20/2023)
// Created on Wed Dec 20 05:01:18 2023

FullAdder1Bit FullAdder1Bit_inst
(
	.A(A_sig) ,	// input  A_sig
	.B(B_sig) ,	// input  B_sig
	.S(S_sig) ,	// output  S_sig
	.Cin(Cin_sig) ,	// input  Cin_sig
	.Co(Co_sig) 	// output  Co_sig
);

