// Copyright (C) 2023  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details, at
// https://fpgasoftware.intel.com/eula.


// Generated by Quartus Prime Version 22.1 (Build Build 922 07/20/2023)
// Created on Mon Dec 11 14:19:59 2023

ALU ALU_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.A(A_sig) ,	// input [7:0] A_sig
	.B(B_sig) ,	// input [7:0] B_sig
	.S(S_sig) ,	// input [3:0] S_sig
	.EQUAL(EQUAL_sig) ,	// output  EQUAL_sig
	.GT(GT_sig) ,	// output  GT_sig
	.LT(LT_sig) ,	// output  LT_sig
	.Zero(Zero_sig) ,	// output  Zero_sig
	.CarryOut(CarryOut_sig) ,	// output  CarryOut_sig
	.Overflow(Overflow_sig) ,	// output  Overflow_sig
	.F(F_sig) ,	// output [7:0] F_sig
	.FF(FF_sig) 	// output [7:0] FF_sig
);

